// Generated by Ignite ignite.com/cli
import { SigningStargateClient } from "@cosmjs/stargate";
import { Registry } from "@cosmjs/proto-signing";
import { msgTypes } from './registry';
import { Api } from "./rest";
import { MsgUpdateParams } from "./types/perpdex/loan/v1/tx";
import { MsgRequestLoan } from "./types/perpdex/loan/v1/tx";
import { MsgCancelLoan } from "./types/perpdex/loan/v1/tx";
import { MsgApproveLoan } from "./types/perpdex/loan/v1/tx";
import { MsgRepayLoan } from "./types/perpdex/loan/v1/tx";
import { MsgLiquidateLoan } from "./types/perpdex/loan/v1/tx";
import { Loan as typeLoan } from "./types";
import { Params as typeParams } from "./types";
export { MsgUpdateParams, MsgRequestLoan, MsgCancelLoan, MsgApproveLoan, MsgRepayLoan, MsgLiquidateLoan };
export const registry = new Registry(msgTypes);
function getStructure(template) {
    const structure = { fields: [] };
    for (let [key, value] of Object.entries(template)) {
        let field = { name: key, type: typeof value };
        structure.fields.push(field);
    }
    return structure;
}
const defaultFee = {
    amount: [],
    gas: "200000",
};
export const txClient = ({ signer, prefix, addr } = { addr: "http://localhost:26657", prefix: "cosmos" }) => {
    return {
        async sendMsgUpdateParams({ value, fee, memo }) {
            if (!signer) {
                throw new Error('TxClient:sendMsgUpdateParams: Unable to sign Tx. Signer is not present.');
            }
            try {
                const { address } = (await signer.getAccounts())[0];
                const signingClient = await SigningStargateClient.connectWithSigner(addr, signer, { registry });
                let msg = this.msgUpdateParams({ value: MsgUpdateParams.fromPartial(value) });
                return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo);
            }
            catch (e) {
                throw new Error('TxClient:sendMsgUpdateParams: Could not broadcast Tx: ' + e.message);
            }
        },
        async sendMsgRequestLoan({ value, fee, memo }) {
            if (!signer) {
                throw new Error('TxClient:sendMsgRequestLoan: Unable to sign Tx. Signer is not present.');
            }
            try {
                const { address } = (await signer.getAccounts())[0];
                const signingClient = await SigningStargateClient.connectWithSigner(addr, signer, { registry });
                let msg = this.msgRequestLoan({ value: MsgRequestLoan.fromPartial(value) });
                return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo);
            }
            catch (e) {
                throw new Error('TxClient:sendMsgRequestLoan: Could not broadcast Tx: ' + e.message);
            }
        },
        async sendMsgCancelLoan({ value, fee, memo }) {
            if (!signer) {
                throw new Error('TxClient:sendMsgCancelLoan: Unable to sign Tx. Signer is not present.');
            }
            try {
                const { address } = (await signer.getAccounts())[0];
                const signingClient = await SigningStargateClient.connectWithSigner(addr, signer, { registry });
                let msg = this.msgCancelLoan({ value: MsgCancelLoan.fromPartial(value) });
                return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo);
            }
            catch (e) {
                throw new Error('TxClient:sendMsgCancelLoan: Could not broadcast Tx: ' + e.message);
            }
        },
        async sendMsgApproveLoan({ value, fee, memo }) {
            if (!signer) {
                throw new Error('TxClient:sendMsgApproveLoan: Unable to sign Tx. Signer is not present.');
            }
            try {
                const { address } = (await signer.getAccounts())[0];
                const signingClient = await SigningStargateClient.connectWithSigner(addr, signer, { registry });
                let msg = this.msgApproveLoan({ value: MsgApproveLoan.fromPartial(value) });
                return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo);
            }
            catch (e) {
                throw new Error('TxClient:sendMsgApproveLoan: Could not broadcast Tx: ' + e.message);
            }
        },
        async sendMsgRepayLoan({ value, fee, memo }) {
            if (!signer) {
                throw new Error('TxClient:sendMsgRepayLoan: Unable to sign Tx. Signer is not present.');
            }
            try {
                const { address } = (await signer.getAccounts())[0];
                const signingClient = await SigningStargateClient.connectWithSigner(addr, signer, { registry });
                let msg = this.msgRepayLoan({ value: MsgRepayLoan.fromPartial(value) });
                return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo);
            }
            catch (e) {
                throw new Error('TxClient:sendMsgRepayLoan: Could not broadcast Tx: ' + e.message);
            }
        },
        async sendMsgLiquidateLoan({ value, fee, memo }) {
            if (!signer) {
                throw new Error('TxClient:sendMsgLiquidateLoan: Unable to sign Tx. Signer is not present.');
            }
            try {
                const { address } = (await signer.getAccounts())[0];
                const signingClient = await SigningStargateClient.connectWithSigner(addr, signer, { registry });
                let msg = this.msgLiquidateLoan({ value: MsgLiquidateLoan.fromPartial(value) });
                return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo);
            }
            catch (e) {
                throw new Error('TxClient:sendMsgLiquidateLoan: Could not broadcast Tx: ' + e.message);
            }
        },
        msgUpdateParams({ value }) {
            try {
                return { typeUrl: "/perpdex.loan.v1.MsgUpdateParams", value: MsgUpdateParams.fromPartial(value) };
            }
            catch (e) {
                throw new Error('TxClient:MsgUpdateParams: Could not create message: ' + e.message);
            }
        },
        msgRequestLoan({ value }) {
            try {
                return { typeUrl: "/perpdex.loan.v1.MsgRequestLoan", value: MsgRequestLoan.fromPartial(value) };
            }
            catch (e) {
                throw new Error('TxClient:MsgRequestLoan: Could not create message: ' + e.message);
            }
        },
        msgCancelLoan({ value }) {
            try {
                return { typeUrl: "/perpdex.loan.v1.MsgCancelLoan", value: MsgCancelLoan.fromPartial(value) };
            }
            catch (e) {
                throw new Error('TxClient:MsgCancelLoan: Could not create message: ' + e.message);
            }
        },
        msgApproveLoan({ value }) {
            try {
                return { typeUrl: "/perpdex.loan.v1.MsgApproveLoan", value: MsgApproveLoan.fromPartial(value) };
            }
            catch (e) {
                throw new Error('TxClient:MsgApproveLoan: Could not create message: ' + e.message);
            }
        },
        msgRepayLoan({ value }) {
            try {
                return { typeUrl: "/perpdex.loan.v1.MsgRepayLoan", value: MsgRepayLoan.fromPartial(value) };
            }
            catch (e) {
                throw new Error('TxClient:MsgRepayLoan: Could not create message: ' + e.message);
            }
        },
        msgLiquidateLoan({ value }) {
            try {
                return { typeUrl: "/perpdex.loan.v1.MsgLiquidateLoan", value: MsgLiquidateLoan.fromPartial(value) };
            }
            catch (e) {
                throw new Error('TxClient:MsgLiquidateLoan: Could not create message: ' + e.message);
            }
        },
    };
};
export const queryClient = ({ addr: addr } = { addr: "http://localhost:1317" }) => {
    return new Api({ baseURL: addr });
};
class SDKModule {
    constructor(client) {
        this.registry = [];
        this.query = queryClient({ addr: client.env.apiURL });
        this.updateTX(client);
        this.structure = {
            Loan: getStructure(typeLoan.fromPartial({})),
            Params: getStructure(typeParams.fromPartial({})),
        };
        client.on('signer-changed', (signer) => {
            this.updateTX(client);
        });
    }
    updateTX(client) {
        const methods = txClient({
            signer: client.signer,
            addr: client.env.rpcURL,
            prefix: client.env.prefix ?? "cosmos",
        });
        this.tx = methods;
        for (let m in methods) {
            this.tx[m] = methods[m].bind(this.tx);
        }
    }
}
;
const IgntModule = (test) => {
    return {
        module: {
            PerpdexLoanV_1: new SDKModule(test)
        },
        registry: msgTypes
    };
};
export default IgntModule;
