// Generated by Ignite ignite.com/cli
import { SigningStargateClient } from "@cosmjs/stargate";
import { Registry } from "@cosmjs/proto-signing";
import { msgTypes } from './registry';
import { Api } from "./rest";
import { MsgUpdateParams } from "./types/perpdex/perpdex/v1/tx";
import { MsgCreatePrice } from "./types/perpdex/perpdex/v1/tx";
import { MsgUpdatePrice } from "./types/perpdex/perpdex/v1/tx";
import { MsgDeletePrice } from "./types/perpdex/perpdex/v1/tx";
import { Params as typeParams } from "./types";
import { Price as typePrice } from "./types";
export { MsgUpdateParams, MsgCreatePrice, MsgUpdatePrice, MsgDeletePrice };
export const registry = new Registry(msgTypes);
function getStructure(template) {
    const structure = { fields: [] };
    for (let [key, value] of Object.entries(template)) {
        let field = { name: key, type: typeof value };
        structure.fields.push(field);
    }
    return structure;
}
const defaultFee = {
    amount: [],
    gas: "200000",
};
export const txClient = ({ signer, prefix, addr } = { addr: "http://localhost:26657", prefix: "cosmos" }) => {
    return {
        async sendMsgUpdateParams({ value, fee, memo }) {
            if (!signer) {
                throw new Error('TxClient:sendMsgUpdateParams: Unable to sign Tx. Signer is not present.');
            }
            try {
                const { address } = (await signer.getAccounts())[0];
                const signingClient = await SigningStargateClient.connectWithSigner(addr, signer, { registry });
                let msg = this.msgUpdateParams({ value: MsgUpdateParams.fromPartial(value) });
                return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo);
            }
            catch (e) {
                throw new Error('TxClient:sendMsgUpdateParams: Could not broadcast Tx: ' + e.message);
            }
        },
        async sendMsgCreatePrice({ value, fee, memo }) {
            if (!signer) {
                throw new Error('TxClient:sendMsgCreatePrice: Unable to sign Tx. Signer is not present.');
            }
            try {
                const { address } = (await signer.getAccounts())[0];
                const signingClient = await SigningStargateClient.connectWithSigner(addr, signer, { registry });
                let msg = this.msgCreatePrice({ value: MsgCreatePrice.fromPartial(value) });
                return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo);
            }
            catch (e) {
                throw new Error('TxClient:sendMsgCreatePrice: Could not broadcast Tx: ' + e.message);
            }
        },
        async sendMsgUpdatePrice({ value, fee, memo }) {
            if (!signer) {
                throw new Error('TxClient:sendMsgUpdatePrice: Unable to sign Tx. Signer is not present.');
            }
            try {
                const { address } = (await signer.getAccounts())[0];
                const signingClient = await SigningStargateClient.connectWithSigner(addr, signer, { registry });
                let msg = this.msgUpdatePrice({ value: MsgUpdatePrice.fromPartial(value) });
                return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo);
            }
            catch (e) {
                throw new Error('TxClient:sendMsgUpdatePrice: Could not broadcast Tx: ' + e.message);
            }
        },
        async sendMsgDeletePrice({ value, fee, memo }) {
            if (!signer) {
                throw new Error('TxClient:sendMsgDeletePrice: Unable to sign Tx. Signer is not present.');
            }
            try {
                const { address } = (await signer.getAccounts())[0];
                const signingClient = await SigningStargateClient.connectWithSigner(addr, signer, { registry });
                let msg = this.msgDeletePrice({ value: MsgDeletePrice.fromPartial(value) });
                return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo);
            }
            catch (e) {
                throw new Error('TxClient:sendMsgDeletePrice: Could not broadcast Tx: ' + e.message);
            }
        },
        msgUpdateParams({ value }) {
            try {
                return { typeUrl: "/perpdex.perpdex.v1.MsgUpdateParams", value: MsgUpdateParams.fromPartial(value) };
            }
            catch (e) {
                throw new Error('TxClient:MsgUpdateParams: Could not create message: ' + e.message);
            }
        },
        msgCreatePrice({ value }) {
            try {
                return { typeUrl: "/perpdex.perpdex.v1.MsgCreatePrice", value: MsgCreatePrice.fromPartial(value) };
            }
            catch (e) {
                throw new Error('TxClient:MsgCreatePrice: Could not create message: ' + e.message);
            }
        },
        msgUpdatePrice({ value }) {
            try {
                return { typeUrl: "/perpdex.perpdex.v1.MsgUpdatePrice", value: MsgUpdatePrice.fromPartial(value) };
            }
            catch (e) {
                throw new Error('TxClient:MsgUpdatePrice: Could not create message: ' + e.message);
            }
        },
        msgDeletePrice({ value }) {
            try {
                return { typeUrl: "/perpdex.perpdex.v1.MsgDeletePrice", value: MsgDeletePrice.fromPartial(value) };
            }
            catch (e) {
                throw new Error('TxClient:MsgDeletePrice: Could not create message: ' + e.message);
            }
        },
    };
};
export const queryClient = ({ addr: addr } = { addr: "http://localhost:1317" }) => {
    return new Api({ baseURL: addr });
};
class SDKModule {
    constructor(client) {
        this.registry = [];
        this.query = queryClient({ addr: client.env.apiURL });
        this.updateTX(client);
        this.structure = {
            Params: getStructure(typeParams.fromPartial({})),
            Price: getStructure(typePrice.fromPartial({})),
        };
        client.on('signer-changed', (signer) => {
            this.updateTX(client);
        });
    }
    updateTX(client) {
        const methods = txClient({
            signer: client.signer,
            addr: client.env.rpcURL,
            prefix: client.env.prefix ?? "cosmos",
        });
        this.tx = methods;
        for (let m in methods) {
            this.tx[m] = methods[m].bind(this.tx);
        }
    }
}
;
const IgntModule = (test) => {
    return {
        module: {
            PerpdexPerpdexV_1: new SDKModule(test)
        },
        registry: msgTypes
    };
};
export default IgntModule;
