// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: perpdex/perpdex/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	io "io"
	math "math"
	math_bits "math/bits"

	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f387ad33372fe94, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f387ad33372fe94, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// QueryShowPriceRequest defines the QueryShowPriceRequest message.
type QueryShowPriceRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryShowPriceRequest) Reset()         { *m = QueryShowPriceRequest{} }
func (m *QueryShowPriceRequest) String() string { return proto.CompactTextString(m) }
func (*QueryShowPriceRequest) ProtoMessage()    {}
func (*QueryShowPriceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f387ad33372fe94, []int{2}
}
func (m *QueryShowPriceRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryShowPriceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryShowPriceRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryShowPriceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryShowPriceRequest.Merge(m, src)
}
func (m *QueryShowPriceRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryShowPriceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryShowPriceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryShowPriceRequest proto.InternalMessageInfo

func (m *QueryShowPriceRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// QueryShowPriceResponse defines the QueryShowPriceResponse message.
type QueryShowPriceResponse struct {
	Post *Price `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
}

func (m *QueryShowPriceResponse) Reset()         { *m = QueryShowPriceResponse{} }
func (m *QueryShowPriceResponse) String() string { return proto.CompactTextString(m) }
func (*QueryShowPriceResponse) ProtoMessage()    {}
func (*QueryShowPriceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f387ad33372fe94, []int{3}
}
func (m *QueryShowPriceResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryShowPriceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryShowPriceResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryShowPriceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryShowPriceResponse.Merge(m, src)
}
func (m *QueryShowPriceResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryShowPriceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryShowPriceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryShowPriceResponse proto.InternalMessageInfo

func (m *QueryShowPriceResponse) GetPost() *Price {
	if m != nil {
		return m.Post
	}
	return nil
}

// QueryShowSymbolPriceRequest defines the QueryShowSymbolPriceRequest message.
type QueryShowSymbolPriceRequest struct {
	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
}

func (m *QueryShowSymbolPriceRequest) Reset()         { *m = QueryShowSymbolPriceRequest{} }
func (m *QueryShowSymbolPriceRequest) String() string { return proto.CompactTextString(m) }
func (*QueryShowSymbolPriceRequest) ProtoMessage()    {}
func (*QueryShowSymbolPriceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f387ad33372fe94, []int{4}
}
func (m *QueryShowSymbolPriceRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryShowSymbolPriceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryShowSymbolPriceRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryShowSymbolPriceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryShowSymbolPriceRequest.Merge(m, src)
}
func (m *QueryShowSymbolPriceRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryShowSymbolPriceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryShowSymbolPriceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryShowSymbolPriceRequest proto.InternalMessageInfo

func (m *QueryShowSymbolPriceRequest) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

// QueryShowSymbolPriceResponse defines the QueryShowSymbolPriceResponse message.
type QueryShowSymbolPriceResponse struct {
	Post *Price `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
}

func (m *QueryShowSymbolPriceResponse) Reset()         { *m = QueryShowSymbolPriceResponse{} }
func (m *QueryShowSymbolPriceResponse) String() string { return proto.CompactTextString(m) }
func (*QueryShowSymbolPriceResponse) ProtoMessage()    {}
func (*QueryShowSymbolPriceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f387ad33372fe94, []int{5}
}
func (m *QueryShowSymbolPriceResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryShowSymbolPriceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryShowSymbolPriceResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryShowSymbolPriceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryShowSymbolPriceResponse.Merge(m, src)
}
func (m *QueryShowSymbolPriceResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryShowSymbolPriceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryShowSymbolPriceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryShowSymbolPriceResponse proto.InternalMessageInfo

func (m *QueryShowSymbolPriceResponse) GetPost() *Price {
	if m != nil {
		return m.Post
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "perpdex.perpdex.v1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "perpdex.perpdex.v1.QueryParamsResponse")
	proto.RegisterType((*QueryShowPriceRequest)(nil), "perpdex.perpdex.v1.QueryShowPriceRequest")
	proto.RegisterType((*QueryShowPriceResponse)(nil), "perpdex.perpdex.v1.QueryShowPriceResponse")
	proto.RegisterType((*QueryShowSymbolPriceRequest)(nil), "perpdex.perpdex.v1.QueryShowSymbolPriceRequest")
	proto.RegisterType((*QueryShowSymbolPriceResponse)(nil), "perpdex.perpdex.v1.QueryShowSymbolPriceResponse")
}

func init() { proto.RegisterFile("perpdex/perpdex/v1/query.proto", fileDescriptor_6f387ad33372fe94) }

var fileDescriptor_6f387ad33372fe94 = []byte{
	// 474 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0xc1, 0x6e, 0xd3, 0x30,
	0x18, 0xc7, 0xeb, 0x32, 0x22, 0xd5, 0x48, 0x20, 0xcc, 0x18, 0x10, 0xaa, 0x0c, 0x19, 0xc1, 0xa0,
	0x88, 0x78, 0x19, 0x82, 0x1b, 0x97, 0x5d, 0x38, 0x21, 0x8d, 0x8c, 0x13, 0x17, 0xe4, 0x2c, 0x56,
	0x66, 0x69, 0xc9, 0xe7, 0xc5, 0x59, 0x47, 0x85, 0x7a, 0xe1, 0x05, 0x40, 0xe2, 0x25, 0x38, 0x70,
	0xe0, 0x2d, 0xd8, 0x71, 0x12, 0x17, 0x4e, 0x08, 0xb5, 0x48, 0xbc, 0x06, 0xaa, 0xed, 0x0c, 0xad,
	0x4d, 0xa1, 0xda, 0xa5, 0x89, 0x3f, 0xff, 0xff, 0xff, 0xef, 0xd7, 0xcf, 0x0e, 0x0e, 0x94, 0x28,
	0x55, 0x2a, 0xde, 0xb0, 0xfa, 0xd9, 0x8f, 0xd8, 0xfe, 0x81, 0x28, 0x07, 0xa1, 0x2a, 0xa1, 0x02,
	0x42, 0x5c, 0x3d, 0xac, 0x9f, 0xfd, 0xc8, 0xbf, 0xcc, 0x73, 0x59, 0x00, 0x33, 0xbf, 0x56, 0xe6,
	0xf7, 0x76, 0x40, 0xe7, 0xa0, 0x59, 0xc2, 0xb5, 0xb0, 0x7e, 0xd6, 0x8f, 0x12, 0x51, 0xf1, 0x88,
	0x29, 0x9e, 0xc9, 0x82, 0x57, 0x12, 0x0a, 0xa7, 0x5d, 0xce, 0x20, 0x03, 0xf3, 0xca, 0x26, 0x6f,
	0xae, 0xda, 0xcd, 0x00, 0xb2, 0x3d, 0xc1, 0xb8, 0x92, 0x8c, 0x17, 0x05, 0x54, 0xc6, 0xa2, 0xdd,
	0xee, 0x6a, 0x03, 0xa6, 0xe2, 0x25, 0xcf, 0x6b, 0x41, 0xd3, 0xff, 0x50, 0xa5, 0xdc, 0x11, 0x76,
	0x9f, 0x2e, 0x63, 0xf2, 0x62, 0x82, 0xb5, 0x65, 0x4c, 0xb1, 0xd8, 0x3f, 0x10, 0xba, 0xa2, 0x2f,
	0xf1, 0x95, 0x53, 0x55, 0xad, 0xa0, 0xd0, 0x82, 0x3c, 0xc5, 0x9e, 0x0d, 0xbf, 0x8e, 0x6e, 0xa1,
	0x7b, 0x17, 0x36, 0xfc, 0x70, 0x76, 0x0a, 0xa1, 0xf5, 0x6c, 0x76, 0x8e, 0x7e, 0xac, 0xb6, 0x3e,
	0xfd, 0xfe, 0xd2, 0x43, 0xb1, 0x33, 0xd1, 0x35, 0x7c, 0xd5, 0xa4, 0x6e, 0xef, 0xc2, 0xe1, 0xd6,
	0x84, 0xc1, 0xb5, 0x23, 0x17, 0x71, 0x5b, 0xa6, 0x26, 0x73, 0x29, 0x6e, 0xcb, 0x94, 0x3e, 0xc3,
	0x2b, 0xd3, 0x42, 0x47, 0xf0, 0x10, 0x2f, 0x29, 0xd0, 0x95, 0xeb, 0x7f, 0xa3, 0xb1, 0xbf, 0x31,
	0x18, 0x19, 0x7d, 0x8c, 0x6f, 0x9e, 0x04, 0x6d, 0x0f, 0xf2, 0x04, 0xf6, 0x4e, 0xf5, 0x5d, 0xc1,
	0x9e, 0x36, 0x55, 0x93, 0xd7, 0x89, 0xdd, 0x8a, 0x3e, 0xc7, 0xdd, 0x66, 0xdb, 0x99, 0x28, 0x36,
	0xbe, 0x9e, 0xc3, 0xe7, 0x4d, 0x1e, 0x19, 0x62, 0xcf, 0x8e, 0x87, 0xdc, 0x6d, 0x32, 0xcd, 0x9e,
	0x84, 0xbf, 0xf6, 0x5f, 0x9d, 0x65, 0xa2, 0xf4, 0xdd, 0xb7, 0x5f, 0x1f, 0xdb, 0x5d, 0xe2, 0xb3,
	0xb9, 0x57, 0x82, 0xbc, 0x47, 0xb8, 0x73, 0x32, 0x53, 0x72, 0x7f, 0x6e, 0xf4, 0xf4, 0x01, 0xf9,
	0xbd, 0x45, 0xa4, 0x0e, 0xe4, 0x81, 0x01, 0xb9, 0x43, 0x6e, 0x37, 0x81, 0xe8, 0x5d, 0x38, 0x7c,
	0x6d, 0xee, 0x1f, 0x7b, 0x2b, 0xd3, 0x21, 0xf9, 0x8c, 0xf0, 0xa5, 0xa9, 0x29, 0x13, 0xf6, 0xcf,
	0x66, 0xb3, 0xc7, 0xe8, 0xaf, 0x2f, 0x6e, 0x70, 0x8c, 0x4f, 0x0c, 0xe3, 0x3a, 0x09, 0xe7, 0x32,
	0xda, 0x9b, 0x50, 0xa3, 0xda, 0xd5, 0x70, 0x33, 0x3a, 0x1a, 0x05, 0xe8, 0x78, 0x14, 0xa0, 0x9f,
	0xa3, 0x00, 0x7d, 0x18, 0x07, 0xad, 0xe3, 0x71, 0xd0, 0xfa, 0x3e, 0x0e, 0x5a, 0xaf, 0xae, 0xd5,
	0x01, 0x7f, 0xa3, 0xaa, 0x81, 0x12, 0x3a, 0xf1, 0xcc, 0x77, 0xf6, 0xe8, 0x4f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x7c, 0x9b, 0x2e, 0x38, 0x51, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// ShowPrice Queries a list of ShowPrice items.
	ShowPrice(ctx context.Context, in *QueryShowPriceRequest, opts ...grpc.CallOption) (*QueryShowPriceResponse, error)
	// ShowSymbolPrice Queries a list of ShowSymbolPrice items.
	ShowSymbolPrice(ctx context.Context, in *QueryShowSymbolPriceRequest, opts ...grpc.CallOption) (*QueryShowSymbolPriceResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/perpdex.perpdex.v1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ShowPrice(ctx context.Context, in *QueryShowPriceRequest, opts ...grpc.CallOption) (*QueryShowPriceResponse, error) {
	out := new(QueryShowPriceResponse)
	err := c.cc.Invoke(ctx, "/perpdex.perpdex.v1.Query/ShowPrice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ShowSymbolPrice(ctx context.Context, in *QueryShowSymbolPriceRequest, opts ...grpc.CallOption) (*QueryShowSymbolPriceResponse, error) {
	out := new(QueryShowSymbolPriceResponse)
	err := c.cc.Invoke(ctx, "/perpdex.perpdex.v1.Query/ShowSymbolPrice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// ShowPrice Queries a list of ShowPrice items.
	ShowPrice(context.Context, *QueryShowPriceRequest) (*QueryShowPriceResponse, error)
	// ShowSymbolPrice Queries a list of ShowSymbolPrice items.
	ShowSymbolPrice(context.Context, *QueryShowSymbolPriceRequest) (*QueryShowSymbolPriceResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) ShowPrice(ctx context.Context, req *QueryShowPriceRequest) (*QueryShowPriceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShowPrice not implemented")
}
func (*UnimplementedQueryServer) ShowSymbolPrice(ctx context.Context, req *QueryShowSymbolPriceRequest) (*QueryShowSymbolPriceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShowSymbolPrice not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/perpdex.perpdex.v1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ShowPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryShowPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ShowPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/perpdex.perpdex.v1.Query/ShowPrice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ShowPrice(ctx, req.(*QueryShowPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ShowSymbolPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryShowSymbolPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ShowSymbolPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/perpdex.perpdex.v1.Query/ShowSymbolPrice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ShowSymbolPrice(ctx, req.(*QueryShowSymbolPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "perpdex.perpdex.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "ShowPrice",
			Handler:    _Query_ShowPrice_Handler,
		},
		{
			MethodName: "ShowSymbolPrice",
			Handler:    _Query_ShowSymbolPrice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "perpdex/perpdex/v1/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryShowPriceRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryShowPriceRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryShowPriceRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryShowPriceResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryShowPriceResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryShowPriceResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Post != nil {
		{
			size, err := m.Post.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryShowSymbolPriceRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryShowSymbolPriceRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryShowSymbolPriceRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Symbol) > 0 {
		i -= len(m.Symbol)
		copy(dAtA[i:], m.Symbol)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Symbol)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryShowSymbolPriceResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryShowSymbolPriceResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryShowSymbolPriceResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Post != nil {
		{
			size, err := m.Post.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryShowPriceRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryShowPriceResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Post != nil {
		l = m.Post.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryShowSymbolPriceRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Symbol)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryShowSymbolPriceResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Post != nil {
		l = m.Post.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryShowPriceRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryShowPriceRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryShowPriceRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryShowPriceResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryShowPriceResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryShowPriceResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Post", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Post == nil {
				m.Post = &Price{}
			}
			if err := m.Post.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryShowSymbolPriceRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryShowSymbolPriceRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryShowSymbolPriceRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Symbol", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Symbol = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryShowSymbolPriceResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryShowSymbolPriceResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryShowSymbolPriceResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Post", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Post == nil {
				m.Post = &Price{}
			}
			if err := m.Post.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
