// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: perpdex/perp/v1/position.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Position defines the Position message.
type Position struct {
	Index      string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	Trader     string `protobuf:"bytes,2,opt,name=trader,proto3" json:"trader,omitempty"`
	Pair       string `protobuf:"bytes,3,opt,name=pair,proto3" json:"pair,omitempty"`
	Side       string `protobuf:"bytes,4,opt,name=side,proto3" json:"side,omitempty"`
	Size_      string `protobuf:"bytes,5,opt,name=size,proto3" json:"size,omitempty"`
	EntryPrice string `protobuf:"bytes,6,opt,name=entry_price,json=entryPrice,proto3" json:"entry_price,omitempty"`
	Margin     string `protobuf:"bytes,7,opt,name=margin,proto3" json:"margin,omitempty"`
	Leverage   string `protobuf:"bytes,8,opt,name=leverage,proto3" json:"leverage,omitempty"`
}

func (m *Position) Reset()         { *m = Position{} }
func (m *Position) String() string { return proto.CompactTextString(m) }
func (*Position) ProtoMessage()    {}
func (*Position) Descriptor() ([]byte, []int) {
	return fileDescriptor_37c76800c22e9086, []int{0}
}
func (m *Position) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Position) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Position.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Position) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Position.Merge(m, src)
}
func (m *Position) XXX_Size() int {
	return m.Size()
}
func (m *Position) XXX_DiscardUnknown() {
	xxx_messageInfo_Position.DiscardUnknown(m)
}

var xxx_messageInfo_Position proto.InternalMessageInfo

func (m *Position) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *Position) GetTrader() string {
	if m != nil {
		return m.Trader
	}
	return ""
}

func (m *Position) GetPair() string {
	if m != nil {
		return m.Pair
	}
	return ""
}

func (m *Position) GetSide() string {
	if m != nil {
		return m.Side
	}
	return ""
}

func (m *Position) GetSize_() string {
	if m != nil {
		return m.Size_
	}
	return ""
}

func (m *Position) GetEntryPrice() string {
	if m != nil {
		return m.EntryPrice
	}
	return ""
}

func (m *Position) GetMargin() string {
	if m != nil {
		return m.Margin
	}
	return ""
}

func (m *Position) GetLeverage() string {
	if m != nil {
		return m.Leverage
	}
	return ""
}

func init() {
	proto.RegisterType((*Position)(nil), "perpdex.perp.v1.Position")
}

func init() { proto.RegisterFile("perpdex/perp/v1/position.proto", fileDescriptor_37c76800c22e9086) }

var fileDescriptor_37c76800c22e9086 = []byte{
	// 253 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x90, 0xcf, 0x4a, 0xc4, 0x30,
	0x10, 0xc6, 0x1b, 0xdd, 0xad, 0x35, 0x1e, 0x84, 0x20, 0x12, 0x3c, 0x44, 0xf1, 0xa2, 0xa7, 0x86,
	0xda, 0x27, 0xd0, 0x27, 0x58, 0x3c, 0x7a, 0x91, 0x6e, 0x3b, 0xd4, 0x80, 0xdb, 0x84, 0x69, 0x2c,
	0xdb, 0x7d, 0x0a, 0x1f, 0x4b, 0x6f, 0x7b, 0xf4, 0x28, 0xed, 0x8b, 0x48, 0xfe, 0xac, 0xa7, 0x99,
	0xdf, 0xef, 0x1b, 0x18, 0xf8, 0xa8, 0x30, 0x80, 0xa6, 0x81, 0xad, 0x74, 0x53, 0x0e, 0x85, 0x34,
	0xba, 0x57, 0x56, 0xe9, 0x2e, 0x37, 0xa8, 0xad, 0x66, 0xe7, 0x31, 0xcf, 0xdd, 0xcc, 0x87, 0xe2,
	0xf6, 0x9b, 0xd0, 0x6c, 0x15, 0x6f, 0xd8, 0x05, 0x5d, 0xaa, 0xae, 0x81, 0x2d, 0x27, 0x37, 0xe4,
	0xfe, 0xf4, 0x39, 0x00, 0xbb, 0xa4, 0xa9, 0xc5, 0xaa, 0x01, 0xe4, 0x47, 0x5e, 0x47, 0x62, 0x8c,
	0x2e, 0x4c, 0xa5, 0x90, 0x1f, 0x7b, 0xeb, 0x77, 0xe7, 0x7a, 0xd5, 0x00, 0x5f, 0x04, 0xe7, 0xf6,
	0xe0, 0x76, 0xc0, 0x97, 0x07, 0xb7, 0x03, 0x76, 0x4d, 0xcf, 0xa0, 0xb3, 0x38, 0xbe, 0x1a, 0x54,
	0x35, 0xf0, 0xd4, 0x47, 0xd4, 0xab, 0x95, 0x33, 0xee, 0xe9, 0xa6, 0xc2, 0x56, 0x75, 0xfc, 0x24,
	0x3c, 0x0d, 0xc4, 0xae, 0x68, 0xf6, 0x0e, 0x03, 0x60, 0xd5, 0x02, 0xcf, 0x7c, 0xf2, 0xcf, 0x4f,
	0x8f, 0x5f, 0x93, 0x20, 0xfb, 0x49, 0x90, 0xdf, 0x49, 0x90, 0xcf, 0x59, 0x24, 0xfb, 0x59, 0x24,
	0x3f, 0xb3, 0x48, 0x5e, 0xee, 0x5a, 0x65, 0xdf, 0x3e, 0xd6, 0x79, 0xad, 0x37, 0xb2, 0xc6, 0xf1,
	0xa1, 0x28, 0x4b, 0x79, 0x68, 0x2a, 0x76, 0x65, 0x47, 0x03, 0xfd, 0x3a, 0xf5, 0x35, 0x95, 0x7f,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x20, 0x51, 0xb7, 0x36, 0x48, 0x01, 0x00, 0x00,
}

func (m *Position) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Position) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Position) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Leverage) > 0 {
		i -= len(m.Leverage)
		copy(dAtA[i:], m.Leverage)
		i = encodeVarintPosition(dAtA, i, uint64(len(m.Leverage)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.Margin) > 0 {
		i -= len(m.Margin)
		copy(dAtA[i:], m.Margin)
		i = encodeVarintPosition(dAtA, i, uint64(len(m.Margin)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.EntryPrice) > 0 {
		i -= len(m.EntryPrice)
		copy(dAtA[i:], m.EntryPrice)
		i = encodeVarintPosition(dAtA, i, uint64(len(m.EntryPrice)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Size_) > 0 {
		i -= len(m.Size_)
		copy(dAtA[i:], m.Size_)
		i = encodeVarintPosition(dAtA, i, uint64(len(m.Size_)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Side) > 0 {
		i -= len(m.Side)
		copy(dAtA[i:], m.Side)
		i = encodeVarintPosition(dAtA, i, uint64(len(m.Side)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Pair) > 0 {
		i -= len(m.Pair)
		copy(dAtA[i:], m.Pair)
		i = encodeVarintPosition(dAtA, i, uint64(len(m.Pair)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Trader) > 0 {
		i -= len(m.Trader)
		copy(dAtA[i:], m.Trader)
		i = encodeVarintPosition(dAtA, i, uint64(len(m.Trader)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintPosition(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintPosition(dAtA []byte, offset int, v uint64) int {
	offset -= sovPosition(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Position) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovPosition(uint64(l))
	}
	l = len(m.Trader)
	if l > 0 {
		n += 1 + l + sovPosition(uint64(l))
	}
	l = len(m.Pair)
	if l > 0 {
		n += 1 + l + sovPosition(uint64(l))
	}
	l = len(m.Side)
	if l > 0 {
		n += 1 + l + sovPosition(uint64(l))
	}
	l = len(m.Size_)
	if l > 0 {
		n += 1 + l + sovPosition(uint64(l))
	}
	l = len(m.EntryPrice)
	if l > 0 {
		n += 1 + l + sovPosition(uint64(l))
	}
	l = len(m.Margin)
	if l > 0 {
		n += 1 + l + sovPosition(uint64(l))
	}
	l = len(m.Leverage)
	if l > 0 {
		n += 1 + l + sovPosition(uint64(l))
	}
	return n
}

func sovPosition(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPosition(x uint64) (n int) {
	return sovPosition(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Position) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPosition
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Position: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Position: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPosition
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPosition
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPosition
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Trader", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPosition
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPosition
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPosition
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Trader = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pair", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPosition
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPosition
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPosition
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Pair = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Side", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPosition
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPosition
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPosition
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Side = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Size_", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPosition
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPosition
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPosition
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Size_ = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EntryPrice", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPosition
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPosition
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPosition
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EntryPrice = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Margin", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPosition
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPosition
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPosition
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Margin = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Leverage", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPosition
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPosition
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPosition
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Leverage = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPosition(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPosition
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPosition(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPosition
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPosition
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPosition
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPosition
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPosition
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPosition
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPosition        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPosition          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPosition = fmt.Errorf("proto: unexpected end of group")
)
