// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: perpdex/perpdex/v1/query.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { PageRequest, PageResponse } from "../../../cosmos/base/query/v1beta1/pagination";
import { Params } from "./params";
import { Price } from "./price";

export const protobufPackage = "perpdex.perpdex.v1";

/** QueryParamsRequest is request type for the Query/Params RPC method. */
export interface QueryParamsRequest {
}

/** QueryParamsResponse is response type for the Query/Params RPC method. */
export interface QueryParamsResponse {
  /** params holds all the parameters of this module. */
  params: Params | undefined;
}

/** QueryShowPriceRequest defines the QueryShowPriceRequest message. */
export interface QueryShowPriceRequest {
  id: number;
}

/** QueryShowPriceResponse defines the QueryShowPriceResponse message. */
export interface QueryShowPriceResponse {
  post: Price | undefined;
}

/** QueryShowSymbolPriceRequest defines the QueryShowSymbolPriceRequest message. */
export interface QueryShowSymbolPriceRequest {
  symbol: string;
}

/** QueryShowSymbolPriceResponse defines the QueryShowSymbolPriceResponse message. */
export interface QueryShowSymbolPriceResponse {
  post: Price | undefined;
}

/** QueryListPriceRequest defines the QueryListPriceRequest message. */
export interface QueryListPriceRequest {
  pagination: PageRequest | undefined;
}

/** QueryListPriceResponse defines the QueryListPriceResponse message. */
export interface QueryListPriceResponse {
  post: Price[];
  pagination: PageResponse | undefined;
}

function createBaseQueryParamsRequest(): QueryParamsRequest {
  return {};
}

export const QueryParamsRequest: MessageFns<QueryParamsRequest> = {
  encode(_: QueryParamsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryParamsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryParamsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): QueryParamsRequest {
    return {};
  },

  toJSON(_: QueryParamsRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryParamsRequest>, I>>(base?: I): QueryParamsRequest {
    return QueryParamsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryParamsRequest>, I>>(_: I): QueryParamsRequest {
    const message = createBaseQueryParamsRequest();
    return message;
  },
};

function createBaseQueryParamsResponse(): QueryParamsResponse {
  return { params: undefined };
}

export const QueryParamsResponse: MessageFns<QueryParamsResponse> = {
  encode(message: QueryParamsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.params !== undefined) {
      Params.encode(message.params, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryParamsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryParamsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.params = Params.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryParamsResponse {
    return { params: isSet(object.params) ? Params.fromJSON(object.params) : undefined };
  },

  toJSON(message: QueryParamsResponse): unknown {
    const obj: any = {};
    if (message.params !== undefined) {
      obj.params = Params.toJSON(message.params);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryParamsResponse>, I>>(base?: I): QueryParamsResponse {
    return QueryParamsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryParamsResponse>, I>>(object: I): QueryParamsResponse {
    const message = createBaseQueryParamsResponse();
    message.params = (object.params !== undefined && object.params !== null)
      ? Params.fromPartial(object.params)
      : undefined;
    return message;
  },
};

function createBaseQueryShowPriceRequest(): QueryShowPriceRequest {
  return { id: 0 };
}

export const QueryShowPriceRequest: MessageFns<QueryShowPriceRequest> = {
  encode(message: QueryShowPriceRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint64(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryShowPriceRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryShowPriceRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryShowPriceRequest {
    return { id: isSet(object.id) ? globalThis.Number(object.id) : 0 };
  },

  toJSON(message: QueryShowPriceRequest): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryShowPriceRequest>, I>>(base?: I): QueryShowPriceRequest {
    return QueryShowPriceRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryShowPriceRequest>, I>>(object: I): QueryShowPriceRequest {
    const message = createBaseQueryShowPriceRequest();
    message.id = object.id ?? 0;
    return message;
  },
};

function createBaseQueryShowPriceResponse(): QueryShowPriceResponse {
  return { post: undefined };
}

export const QueryShowPriceResponse: MessageFns<QueryShowPriceResponse> = {
  encode(message: QueryShowPriceResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.post !== undefined) {
      Price.encode(message.post, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryShowPriceResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryShowPriceResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.post = Price.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryShowPriceResponse {
    return { post: isSet(object.post) ? Price.fromJSON(object.post) : undefined };
  },

  toJSON(message: QueryShowPriceResponse): unknown {
    const obj: any = {};
    if (message.post !== undefined) {
      obj.post = Price.toJSON(message.post);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryShowPriceResponse>, I>>(base?: I): QueryShowPriceResponse {
    return QueryShowPriceResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryShowPriceResponse>, I>>(object: I): QueryShowPriceResponse {
    const message = createBaseQueryShowPriceResponse();
    message.post = (object.post !== undefined && object.post !== null) ? Price.fromPartial(object.post) : undefined;
    return message;
  },
};

function createBaseQueryShowSymbolPriceRequest(): QueryShowSymbolPriceRequest {
  return { symbol: "" };
}

export const QueryShowSymbolPriceRequest: MessageFns<QueryShowSymbolPriceRequest> = {
  encode(message: QueryShowSymbolPriceRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.symbol !== "") {
      writer.uint32(10).string(message.symbol);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryShowSymbolPriceRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryShowSymbolPriceRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.symbol = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryShowSymbolPriceRequest {
    return { symbol: isSet(object.symbol) ? globalThis.String(object.symbol) : "" };
  },

  toJSON(message: QueryShowSymbolPriceRequest): unknown {
    const obj: any = {};
    if (message.symbol !== "") {
      obj.symbol = message.symbol;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryShowSymbolPriceRequest>, I>>(base?: I): QueryShowSymbolPriceRequest {
    return QueryShowSymbolPriceRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryShowSymbolPriceRequest>, I>>(object: I): QueryShowSymbolPriceRequest {
    const message = createBaseQueryShowSymbolPriceRequest();
    message.symbol = object.symbol ?? "";
    return message;
  },
};

function createBaseQueryShowSymbolPriceResponse(): QueryShowSymbolPriceResponse {
  return { post: undefined };
}

export const QueryShowSymbolPriceResponse: MessageFns<QueryShowSymbolPriceResponse> = {
  encode(message: QueryShowSymbolPriceResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.post !== undefined) {
      Price.encode(message.post, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryShowSymbolPriceResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryShowSymbolPriceResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.post = Price.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryShowSymbolPriceResponse {
    return { post: isSet(object.post) ? Price.fromJSON(object.post) : undefined };
  },

  toJSON(message: QueryShowSymbolPriceResponse): unknown {
    const obj: any = {};
    if (message.post !== undefined) {
      obj.post = Price.toJSON(message.post);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryShowSymbolPriceResponse>, I>>(base?: I): QueryShowSymbolPriceResponse {
    return QueryShowSymbolPriceResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryShowSymbolPriceResponse>, I>>(object: I): QueryShowSymbolPriceResponse {
    const message = createBaseQueryShowSymbolPriceResponse();
    message.post = (object.post !== undefined && object.post !== null) ? Price.fromPartial(object.post) : undefined;
    return message;
  },
};

function createBaseQueryListPriceRequest(): QueryListPriceRequest {
  return { pagination: undefined };
}

export const QueryListPriceRequest: MessageFns<QueryListPriceRequest> = {
  encode(message: QueryListPriceRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.pagination !== undefined) {
      PageRequest.encode(message.pagination, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryListPriceRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryListPriceRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.pagination = PageRequest.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryListPriceRequest {
    return { pagination: isSet(object.pagination) ? PageRequest.fromJSON(object.pagination) : undefined };
  },

  toJSON(message: QueryListPriceRequest): unknown {
    const obj: any = {};
    if (message.pagination !== undefined) {
      obj.pagination = PageRequest.toJSON(message.pagination);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryListPriceRequest>, I>>(base?: I): QueryListPriceRequest {
    return QueryListPriceRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryListPriceRequest>, I>>(object: I): QueryListPriceRequest {
    const message = createBaseQueryListPriceRequest();
    message.pagination = (object.pagination !== undefined && object.pagination !== null)
      ? PageRequest.fromPartial(object.pagination)
      : undefined;
    return message;
  },
};

function createBaseQueryListPriceResponse(): QueryListPriceResponse {
  return { post: [], pagination: undefined };
}

export const QueryListPriceResponse: MessageFns<QueryListPriceResponse> = {
  encode(message: QueryListPriceResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.post) {
      Price.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.pagination !== undefined) {
      PageResponse.encode(message.pagination, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryListPriceResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryListPriceResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.post.push(Price.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.pagination = PageResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryListPriceResponse {
    return {
      post: globalThis.Array.isArray(object?.post) ? object.post.map((e: any) => Price.fromJSON(e)) : [],
      pagination: isSet(object.pagination) ? PageResponse.fromJSON(object.pagination) : undefined,
    };
  },

  toJSON(message: QueryListPriceResponse): unknown {
    const obj: any = {};
    if (message.post?.length) {
      obj.post = message.post.map((e) => Price.toJSON(e));
    }
    if (message.pagination !== undefined) {
      obj.pagination = PageResponse.toJSON(message.pagination);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryListPriceResponse>, I>>(base?: I): QueryListPriceResponse {
    return QueryListPriceResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryListPriceResponse>, I>>(object: I): QueryListPriceResponse {
    const message = createBaseQueryListPriceResponse();
    message.post = object.post?.map((e) => Price.fromPartial(e)) || [];
    message.pagination = (object.pagination !== undefined && object.pagination !== null)
      ? PageResponse.fromPartial(object.pagination)
      : undefined;
    return message;
  },
};

/** Query defines the gRPC querier service. */
export interface Query {
  /** Parameters queries the parameters of the module. */
  Params(request: QueryParamsRequest): Promise<QueryParamsResponse>;
  /** ShowPrice Queries a list of ShowPrice items. */
  ShowPrice(request: QueryShowPriceRequest): Promise<QueryShowPriceResponse>;
  /** ShowSymbolPrice Queries a list of ShowSymbolPrice items. */
  ShowSymbolPrice(request: QueryShowSymbolPriceRequest): Promise<QueryShowSymbolPriceResponse>;
  /** ListPrice Queries a list of ListPrice items. */
  ListPrice(request: QueryListPriceRequest): Promise<QueryListPriceResponse>;
}

export const QueryServiceName = "perpdex.perpdex.v1.Query";
export class QueryClientImpl implements Query {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || QueryServiceName;
    this.rpc = rpc;
    this.Params = this.Params.bind(this);
    this.ShowPrice = this.ShowPrice.bind(this);
    this.ShowSymbolPrice = this.ShowSymbolPrice.bind(this);
    this.ListPrice = this.ListPrice.bind(this);
  }
  Params(request: QueryParamsRequest): Promise<QueryParamsResponse> {
    const data = QueryParamsRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "Params", data);
    return promise.then((data) => QueryParamsResponse.decode(new BinaryReader(data)));
  }

  ShowPrice(request: QueryShowPriceRequest): Promise<QueryShowPriceResponse> {
    const data = QueryShowPriceRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "ShowPrice", data);
    return promise.then((data) => QueryShowPriceResponse.decode(new BinaryReader(data)));
  }

  ShowSymbolPrice(request: QueryShowSymbolPriceRequest): Promise<QueryShowSymbolPriceResponse> {
    const data = QueryShowSymbolPriceRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "ShowSymbolPrice", data);
    return promise.then((data) => QueryShowSymbolPriceResponse.decode(new BinaryReader(data)));
  }

  ListPrice(request: QueryListPriceRequest): Promise<QueryListPriceResponse> {
    const data = QueryListPriceRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "ListPrice", data);
    return promise.then((data) => QueryListPriceResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
